services:
  meshenger:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_UID: "${UID:-1000}"
        APP_GID: "${GID:-1000}"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
    environment:
      RUST_LOG: debug
    working_dir: /data
    volumes:
      - ./config.toml:/config/config.toml:ro
      - ./data:/data
